function [J grad] = nnCostFunction(nn_params, ...
                                   input_layer_size, ...
                                   hidden_layer_size, ...
                                   num_labels, ...
                                   X, y, lambda)

% Native version of nn cost function, more readable
% [J grad] = nnCostFunctionNative(nn_params, ...
%                                 input_layer_size, ...
%                                 hidden_layer_size, ...
%                                 num_labels, ...
%                                 X, y, lambda);

[J grad] = nnCostFunctionOptimized(nn_params, ...
                                input_layer_size, ...
                                hidden_layer_size, ...
                                num_labels, ...
                                X, y, lambda);

% Optimized version of nn cost function, implement by matrix
end
